# Generated by Django 3.2.9 on 2021-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_Body', models.TextField()),
                ('No_of_Q_Options', models.IntegerField()),
                ('Q_Option1', models.TextField()),
                ('Q_Option2', models.TextField()),
                ('Q_Option3', models.TextField()),
                ('Q_Option4', models.TextField()),
                ('Extra_Option', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
