# Generated by Django 3.2.9 on 2021-11-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='No_of_Q_Options',
        ),
    ]
