# Generated by Django 3.2.9 on 2021-11-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_no_of_q_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Q_Option1',
            new_name='Option_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Q_Option2',
            new_name='Option_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Q_Option3',
            new_name='Option_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Q_Option4',
            new_name='Option_4',
        ),
    ]
