# Generated by Django 3.2.9 on 2021-12-14 16:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211210_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Voter_Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
