# Generated by Django 3.2.9 on 2021-12-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vote_voter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Option_1',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_2',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_3',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_4',
            field=models.CharField(blank=True, max_length=110),
        ),
    ]
