# Generated by Django 3.2.9 on 2021-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211109_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Extra_Option',
            field=models.TextField(null=True),
        ),
    ]
