# Generated by Django 3.2.9 on 2021-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_extra_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Extra_Option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_4',
            field=models.TextField(blank=True),
        ),
    ]
