name: kar_zar
description: KarZar Q&A
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


#  fonts:
#  - family: vazir-bold
#    fonts:
#      - asset: assets/Vazir-Bold.ttf
#
#  - family: Vazir-Light
#    fonts:
#      - asset: assets/Vazir-Light.ttf
